server:
  port: 8360

#==================数据库相关配置==================
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///jsp?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

mybatis:
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台打印 sql
    map-underscore-to-camel-case: true                    # 下划线转驼峰配置
  mapper-locations: classpath:mapper/*.xml                # 配置扫描
  type-aliases-package: org.kuro.news.model.entity                # 配置xml的结果别名
