server:
  port: 8360
  compression:
    enabled: true # 开启gzip压缩

spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql:///kuro_blog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    database: 11
  servlet:
    multipart:
      max-file-size: 3MB # 单次最大请求文件大小
      max-request-size: 10MB # 总请求最大文件大小

mybatis:
  type-aliases-package: org.kuro.blog.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台打印 sql
    map-underscore-to-camel-case: true                    # 下划线转驼峰配置
    use-generated-keys: true
  mapper-locations: classpath:mapper/*.xml                # 配置扫描